### ISSUE TITLE
Malformed line comment results in [object Object]

### ISSUE THREAD

**Issue by micahhausler** [rpetrich/deciduous#22]
See https://www.deciduous.app/#gist=1b1460a8d3d9babf3092c5cf8040324c
<img width="538" alt="Screen Shot 2022-01-26 at 10 33 55 AM" src="https://user-images.githubusercontent.com/791000/151194520-c0ebf01b-8205-4053-a86d-fb6ac82d2297.png">

Relevant yaml:
```yaml
- goal3:
  from:
  - attack1:
      implemented: true  # <-- 2 spaces too many
```
